### ISSUE TITLE
Please make SourceType "RequireQualifiedAccess"

### ISSUE THREAD

**Issue by dsyme** [nessos/Streams#13]
[This](https://github.com/nessos/Streams/blob/b8a807710249fe4c83a7f3b2440ab8fc078f50da/src/Streams.Core/ParStreams.fs#L30) discriminated union pollutes the F# namespace taking the names "ResizeArray", "Seq" and "Array"

```
type SourceType =
    | Array
    | ResizeArray
    | Seq
```
For example, after opening Nessos.Streams the code
```
let results = ResizeArray()
```
no longer compiles.  Please add ```[<RequireQualifiedAccess>]``` to this union type?

Please make this Require

**Comment by palladin** [comment]
Sorry for the inconvenience, it is already fixed in master and we will push a new nuget pkg asap.
